# Uncomment the next line to define a global platform for your project


target 'easy-weather-source-file' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for easy-weather-source-file


pod 'Alamofire'
pod 'SwiftyJSON'


end
